name: awsea
services:
  - name: web
    git:
      repo_clone_url: https://github.com/shanepai-14/awseadeploy.git
      branch: main
    run_command: gunicorn -c gunicorn.conf.py app:app
    http_port: 8080
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
