name: wen-devlife
services:
- name: web
  gitlab:
    repo: wendevlife-group/WenDEVLIFE-awseadeploy
    branch: main
  run_command: python app.py
  http_port: 8080
  environment_slug: python
  instance_size_slug: basic-xxs
  instance_count: 1

